       01 OBI-RCTP10.
      *
      *       total length 629
      *
              10   RECORD-TYPE                         PIC   X(08).
              10   RECORD-NUMBER                       PIC   X(12).
              10   ACCOUNT-NUMBER                      PIC   X(32).
              10   BACK-OFFICE-ACCOUNT-TYPE            PIC   X(08).
              10   FILLER-01                           PIC   X(01).
              10   AMOUNT                              PIC   X(12).
              10   DEBIT-CREDIT-INDICATOR              PIC   X(02).
              10   CURRENCY-CODE                       PIC   X(03).
              10   FILLER-02                           PIC   X(01).
              10   EFFECTIVE-DATE                      PIC   X(08).
              10   FILLER-03                           PIC   X(01).
              10   REFERENCE-REF                       PIC   X(16).
              10   FILLER-04                           PIC   X(01).
              10   BACK-OFFICE-TRANSACTION-TYPE        PIC   X(08).
              10   FILLER-05                           PIC   X(01).
              10   USER-ID                             PIC   X(03).
              10   FILLER-06                           PIC   X(01).
              10   CORRESPONDING-ACCOUNT               PIC   X(32).
              10   FRONT-END-TRANSACTION-TYPE          PIC   X(08).
              10   FILLER-07                           PIC   X(01).
              10   TRANSACTION-PLACE                   PIC   X(40).
              10   OPTIONAL-1                          PIC   X(32).
              10   OPTIONAL-2                          PIC   X(32).
              10   OPTIONAL-3                          PIC   X(32).
              10   OPTIONAL-4                          PIC   X(32).
              10   OPTIONAL-5                          PIC   X(32).
              10   OPTIONAL-6                          PIC   X(32).
              10   OPTIONAL-7                          PIC   X(32).
              10   OPTIONAL-8                          PIC   X(32).
              10   TRANSACTIONS-GROUP-ID               PIC   X(12).
              10   ISO-TERMINAL-ID                     PIC   X(08).
              10   ISO-MERCHANT-ID                     PIC   X(15).
              10   FILLER-08                           PIC   X(08).
              10   RETRIEVAL-REFERENCE-NUMBER          PIC   X(12).
              10   SYSTEM-TRACE-AUDIT-NUMBER           PIC   X(06).
              10   FILLER-09                           PIC   X(01).
              10   CARD-CONTRACT-ID                    PIC   X(06).
              10   DEBIT-CREDIT-CONTRACT-IND           PIC   X(01).
              10   INTERNAL-CARD-TYPE                  PIC   X(02).
              10   ACQUIRER-BIN                        PIC   X(06).
              10   ACCOUNT-NUMBER-2                    PIC   X(32).
              10   CURRENCY-CODE-ACCOUNT-NO-2          PIC   X(03).
              10   FILLER-10                           PIC   X(01).
              10   FRONT-END-UNIQUE-TRANS-NO           PIC   X(12).
              10   SERVICE-ID                          PIC   X(08).
              10   EXTERNAL-TRANSACTION-NUMBER         PIC   X(30).
              10   CARD-NETWORK                        PIC   X(03).
              10   SETTLEMENT-TYPE                     PIC   X(08).
